CREATE DATABASE IF NOT EXISTS nestdb;
USE nestdb;

CREATE TABLE IF NOT EXISTS elements (
  id CHAR(36) PRIMARY KEY,
  type VARCHAR(255) NOT NULL,
  x INT NOT NULL,
  y INT NOT NULL,
  width INT NOT NULL,
  height INT NOT NULL,
  opacity INT NOT NULL,
  scale INT NOT NULL,
  props JSON NOT NULL,
  meta JSON NOT NULL,
  userId CHAR(36) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);